apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busubox
spec:
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  containers:
    - name: buxybox
      image: busybox
      command: ["/bin/sh", "-c","sleep 3600"]
    
