apiVersion: batch/v1
metadata:
  name: myapp
kind: Job
spec:
  template:
    spec:
      containers:
        - name: busybox
          image: busybox
          args: 
            - "bin/sh"
            - "-c"
            - "sleep 3600"
          command:
            - "/bin/sh"
            - "-c"
            - "echo hii"
      restartPolicy: OnFailure
#  backoffLimit: 4
#  parallelism: 2
