apiVersion: v1
kind: Pod
metadata:
  name: live
spec:
  containers:
  - name: myapp-container
    image: busybox
    args: 
      - "/bin/sh"
      - "-c"
      - "touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600"
    readinessProbe:
      exec:
        command:
          - cat 
          - /tmp/healthy
      initialDelaySeconds: 4
      periodSeconds: 5	
