apiVersion: v1
kind: Pod
metadata:
  name: empty-vol
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c", "echo hello > /tmp/storage/test.txt && ls /tmp/storage && while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /tmp/storage
      name: empty-volume
  volumes:
  - name: empty-volume
    emptyDir: {}
