apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
  labels:
    app: daemontest
spec:
  selector:
    matchLabels:
      app: daemontest
  template:
    metadata:
      labels:
        app: daemontest
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule  
      containers:
        - name: nginx
          image: nginx
          
