apiVersion: v1
kind: Pod
metadata:
  name: nginx-proxy
  #namespace: myapp
  labels:
    app: nginx-proxy
spec:
  #serviceAccountName: hm
  containers:
  - name: nginx-proxy
    image: neilpang/nginx-proxy
    env:
    - name: VIRTUAL_HOST
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: VIRTUAL_HOST
