apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "touch /mnt/data/welcome.txt && echo hello && pwd  && while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt/data
          name: my-storage
  volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
